http:
  port: 8080

admin: 
  port: 9876
  host: localhost 

apiEndpoints:
  # profile:
  #   - host: localhost
  #     paths: /user_management/profile
  #     methods: ["GET"]
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/profile*
  #     methods: ["POST","DELETE"]
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/profile/agent
  #     methods: ["GET"]
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/image*
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/activity*
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/type-user*
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/category*
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/document*

  #   - host: localhost
  #     paths: /user_management/company*
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/activity-company*
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/profile
  #     scopes: ['admin']

  #   - host: localhost
  #     paths: /user_management/profile/agent
  #     methods: ["POST"]
  #     scopes: ['admin']

  topup:
    host: localhost
    paths: /api/facial
    methods:
      - POST
      
  profile:
    - host: localhost
      paths: /user_management/profile/
      methods: ["GET"]
      scopes: ['admin']

    - host: localhost
      paths: /user_management/profile/
      methods: ["POST"]
      scopes: ['admin']

    - host: localhost
      paths: /user_management/company/profile-by-company
      methods: ["POST"]
      scopes: ['admin']

    - host: localhost
      paths: /user_management/profile/agent
      methods: ["POST"]
      scopes: ['admin']

    - host: localhost
      paths: /user_management/history/*
      methods: ["GET"]
      scopes: ['admin']

  voucher:
    - host: localhost
      paths: /voucher/
      methods: ["GET"]
      scopes: ['admin']

    - host: localhost
      paths: /voucher/facial*
      methods: ["POST"]
      scopes: ['admin']

    # - host: localhost
    #   paths: /voucher/voucher*
    #   methods: ["POST"]
    #   scopes: ['admin']

    - host: localhost
      paths: /voucher/operator*
      methods: ["POST"]
      scopes: ['admin']

    - host: localhost
      paths: /voucher/document
      methods: ["POST"]
      scopes: ['admin']

    - host: localhost
      paths: '/voucher/transaction'
      methods: ["GET"]
      scopes: ['admin']

    - host: localhost
      paths: '/voucher/transaction'
      methods: ["POST"]
      scopes: ['admin']

    - host: localhost
      paths: '/voucher/transaction/by_user/:id'
      methods: ["GET"]
      scopes: ['user']

    - host: localhost
      paths: '/voucher/transaction/status'
      methods: ["POST"]
      scopes: ['admin']

    - host: localhost
      paths: '/voucher/settings'
      methods: ["POST"]
      scopes: ['admin']

    # - host: localhost
    #   paths: /voucher/transaction/
    #   methods: ["GET"]
    #   scopes: ['admin']

  paymee:
    - host: localhost
      paths: /paymee/cashin
      methods: ["POST"]
      scopes: ['user']

    - host: localhost
      paths:  ['/paymee/accountname/:id']
      methods: ["GET"]
      scopes: ['user']

    - host: localhost
      paths: /paymee/transactions
      scopes: ['admin']

  agent-register:
    - host: localhost
      paths: /api/agent-register/profile/agent
      methods: ["POST"]
      scopes: ['agent']

  wallet:
    - host: localhost
      paths: /api/wallet
      methods: ["GET"]
      scopes: ['admin']

  api:
    host: '*'
    scopes: ['super_admin','admin']

    serviceEndpoints:
  profile:
    url: 'http://localhost:5000'
  wallet:
    url: 'http://localhost:5003'
  api_management:
    url: 'http://localhost:3000/api_management'
  backend:
    url: 'http://localhost:9876' 

policies:
  - basic-auth
  - key-auth
  - log
  - proxy
  - oauth2
  - jwt
  - request-transformer
  - validate-user
  - jwt-permissions
  - jwtScopes
  - agent-register
  - rewrite
  - tokenReg
  - login
  - response-transformer

pipelines:
  # default:
  #   apiEndpoints:
  #     - profile
  #   policies:
  #     - log:
  #         - action:
  #             message: "profile eee header===> ${req.headers.authorization} ---${res.statusCode}-${req.method} ${req.originalUrl}  ${req.url}"
  #   # rewrite:
  #   #   -
  #   #     condition:
  #   #       name: pathmatch
  #   #       match: /:route*
  #   #     action:
  #   #       rewrite: /api_management/:route
  #     - log:
  #         - action:
  #             message: "eeerrr header===> ${req.headers.authorization} ---${res.statusCode}-${req.method} ${req.originalUrl}  ${req.url}"
  #     - oauth2:
  #         - action:
  #             jwt:
  #               issuer: express-gateway
  #               audience: something
  #               subject: 3pXQjeklS3cFf8OCJw9B22
  #               secretOrPublicKey: 54v3WJGBcFPh3TFgZSzovw
  #               checkCredentialExistence: false
  #     - validate-user:
  #     - request-transformer:
  #         action:
  #           body:
  #             add:
  #               user: req.user
  #     - log:
  #         - action:
  #             message: "aaaa ${res.statusCode}-${req.method} ${req.originalUrl}  ${req.url}"

  #     - proxy:
  #         - action:
  #             serviceEndpoint: api_management
  #             changeOrigin: true
  voucher:
    apiEndpoints:
      - voucher
    policies:
      - log:
          - action:
              message: "voucher header===> ${req.headers.authorization} ---${req.originalUrl}  ${req.url}"
      - oauth2:
          - action:
              jwt:
                issuer: express-gateway
                audience: something
                subject: 3pXQjeklS3cFf8OCJw9B22
                secretOrPublicKey: 54v3WJGBcFPh3TFgZSzovw
                checkCredentialExistence: false
      - validate-user:
      - request-transformer:
          action:
            body:
              add:
                user: req.user
      - log:
          - action:
              message: "${res.statusCode}-${req.method} ${req.originalUrl}  ${req.url}"
      - proxy:
          - action:
              serviceEndpoint: api_management
              changeOrigin: true
  topup:
    apiEndpoints:
      - topup
    policies:
      - proxy:
          - action:
              serviceEndpoint: api_management
              changeOrigin: true

  profile:
    apiEndpoints:
      - profile
    policies:
      - log:
          - action:
              message: "aerteet header===> ${req.headers.authorization} ---${req}"
      - oauth2:
          - action:
              jwt:
                issuer: express-gateway
                audience: something
                subject: 3pXQjeklS3cFf8OCJw9B22
                secretOrPublicKey: 54v3WJGBcFPh3TFgZSzovw
                checkCredentialExistence: false
      - validate-user:
      - request-transformer:
          action:
            body:
              add:
                user: req.user
      - log:
          - action:
              message: "${res.statusCode}-${req.method} ${req.originalUrl}  ${req.url}"

      - proxy:
          - action:
              serviceEndpoint: api_management
              changeOrigin: true

  paymee:
    apiEndpoints:
      - paymee
    policies:
      - log:
          - action:
              message: "paymee header===> ${req.headers.authorization} ---${req.originalUrl}  ${req.url}"
      - oauth2:
          - action:
              jwt:
                issuer: express-gateway
                audience: something
                subject: 3pXQjeklS3cFf8OCJw9B22
                secretOrPublicKey: 54v3WJGBcFPh3TFgZSzovw
                checkCredentialExistence: false
      - validate-user:
      - request-transformer:
          action:
            body:
              add:
                user: req.user
      - log:
          - action:
              message: "${res.statusCode}-${req.method} ${req.originalUrl}  ${req.url}"

      - proxy:
          - action:
              serviceEndpoint: api_management
              changeOrigin: true
  wallet:
    apiEndpoints:
      - wallet
    policies:
      - log:
          - action:
              message: "wallet header===> ${req.headers.authorization} ---${req.originalUrl}  ${req.url}"
      - oauth2:
          - action:
              jwt:
                issuer: express-gateway
                audience: something
                subject: 3pXQjeklS3cFf8OCJw9B22
                secretOrPublicKey: 54v3WJGBcFPh3TFgZSzovw
                checkCredentialExistence: false
      - validate-user:
      - request-transformer:
          action:
            body:
              add:
                user: req.user
      - log:
          - action:
              message: "${res.statusCode}-${req.method} ${req.originalUrl}  ${req.url}"

      - proxy:
          - action:
              serviceEndpoint: wallet
              changeOrigin: true

  adminAPI:
    apiEndpoints:
      - api
    policies:
      - log:
          - action:
              message: "api admin header===> ${req.headers.authorization} ${req.originalUrl}  ${req.url}"
      # - oauth2:
      #     - action:
      #         jwt:
      #           issuer: express-gateway
      #           audience: something
      #           subject: 3pXQjeklS3cFf8OCJw9B22
      #           secretOrPublicKey: 54v3WJGBcFPh3TFgZSzovw
      #           checkCredentialExistence: false
      # - validate-user:
      - request-transformer:
          action:
            body:
              add:
                user: req.user
      - log:
          - action:
              message: "${res.statusCode}-${req.method} ${req.originalUrl}  ${req.url}"
      - proxy:
          - action:
              serviceEndpoint: backend
              changeOrigin: true

