http:
  port: 8080
# admin:
#   port: 9876
#   host: localhost
apiEndpoints:
  adminAPI:
    host: 'localhost:8081' # 
  profile:
    host: localhost
    paths: /api/profile
    methods:
      - PUT
      - POST
      - PATCH
      - DELETE
      - GET
serviceEndpoints:
  profile:
    url: 'http://localhost:5000'
policies:
  - log
  - proxy
  - key-auth
  - wallet
pipelines:
  profile:
    apiEndpoints:
      - profile
    policies:
      - proxy:
          - action:
              serviceEndpoint: profile
              changeOrigin: true
  adminAPI:
    apiEndpoints:
      - adminAPI
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: adminAPI
              changeOrigin: true
