http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  profile:
    host: localhost
    paths: /api/profile
    methods:
      - PUT
      - POST
      - PATCH
      - DELETE
      - GET
serviceEndpoints:
  profile:
    url: 'http://localhost:5000'
policies:
  - log
  - proxy
pipelines:
  profile:
    apiEndpoints:
      - profile
    policies:
      - proxy:
          - action:
              serviceEndpoint: profile
              changeOrigin: true
