# Core
# db:
#   redis:
#     emulate: true
#     namespace: EG
db:
  redis:
    host: localhost
    port: 6379
    namespace: EG
#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config'


  # Express gateway does not store passwords in plain text. It converts hashes them. This section controlls how passwords are converted.
crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# Express Gateway does not need session to work. The only part that requires it is Authorization Code flow of OAuth 2.0 built in server.
# OAuth2 Settings
# This section controls Lifetime of Access Tokens issued by built in OAuth 2.0 server at during one of authorization flows as well as the type of token to be issued.

# accessTokens:
#   timeToExpiry: 7200000
#   tokenType: 'jwt'
#   issuer: 'express-gateway'
#   audience: 'something'
#   subject: 'test'
#   secretOrPrivateKey: 'secret'


session:
  secret: khallsli-paypos
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
  tokenType: 'jwt'
  issuer: 'express-gateway'
  audience: 'something'
  subject: '3pXQjeklS3cFf8OCJw9B22'
  secretOrPrivateKey: '54v3WJGBcFPh3TFgZSzovw'
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

  # timeToExpiry: 7200000   en seconde cad 83jrs
  # timeToExpiry: 7200   en seconde cad 2jrs



# session:
#   secret: khallsli-paypos
#   resave: false
#   saveUninitialized: false
# accessTokens:
#   timeToExpiry: 7200000
#   tokenType: 'jwt'
#   issuer: 'express-gateway'
#   audience: 'something'
#   subject: 'test'
#   secretOrPublicKeyFile: config/public.pem
# refreshTokens:
#   timeToExpiry: 7200000
# authorizationCodes:
#   timeToExpiry: 300000

# this is with pass credentials
# session:
#   secret: khallsli-paypos
#   resave: false
#   saveUninitialized: false
# accessTokens:
#   timeToExpiry: 7200000
#   tokenType: 'jwt'
#   issuer: 'express-gateway'
#   audience: 'something'
#   subject: 'test'
#   secretOrPrivateKey: 'secret'
# refreshTokens:
#   timeToExpiry: 7200000
# authorizationCodes:
#   timeToExpiry: 300000

plugins:
  wallet:
    package: "../../../plugins/wallet/manifest.js"
  register:
    package: "../../../plugins/register/manifest.js"
  voucher:
    package: "../../../plugins/voucher/manifest.js"
  bodyParser:
    package: "../../../plugins/bodyParser/manifest.js"
  validate-user:
    package: "../../../plugins/validate-user.js"
  jwt-permissions:
    package: express-gateway-plugin-jwt-permissions
  jwtScopes:
    package: "../../../plugins/jwtScopes.js"
  agent-register:
    package: "../../../plugins/agent-register.js"
  rewrite:
    package: express-gateway-plugin-rewrite